export const ru_language = {
    "auth": "Авторизация",
    "reg": "Регистрация",
    "recovery": "Восстановление",
    "error_password": "Неправильный пароль, попробуйте еще раз.",
    "not_active_account": "Ваш аккаунт не активен. Вам выслано новое сообщение с активацией.",
    "not_fields": "Заполните поля.",
    "not_auth": "Пользователь не зарегистрирован.",
    "next_email": "Продолжить с почтой",
    "next_pass": "Продолжить с паролем",
    "next_username": "Продолжить с имени пользователя",
    "forgot_pass": "Забыли пароль?",
    "authentification": " Уже зарегестрированы? ",
    "authorization": "Войти",
    "not_register": " Не зарегистрированы? ",
    "register": "Зарегистрироваться" ,
    "enter_pass": "Введите ваш пароль...",
    "enter_re_pass": "Введите ваш пароль еще раз...",
    "enter_email": "Введите вашу почту...",
    "enter_username": "Введите ваше имя пользователя...",
    "active_email": "Пользователь с такой почтой уже зарегистрирован.",
    "password_common": "Введённый пароль слишком широко распространён. Попробуйте другой.",
    "not_email_aviable": "Введите правильный адрес электронной почты!",
    "password_match": "Пароли не совпадают.",
    "password_numbers": "Введённый пароль состоит только из цифр. Попробуйте другой.",
    "password_short": "Введённый пароль слишком короткий. Он должен содержать как минимум 8 символов!",
    "active_username": "Пользователь с таким именем уже зарегистрирован.",
    "activation": "Сообщение с активацией отправлено на почту.",
    "activation_reset": "Сообщение с инструкцией отправлено повторно на почту. Через несколько секунд вы будете перенаправлены.",
    "error_mail_send": "Ошибка при отправке сообщения",
    "captcha_input": "Введите код сюда...",
    "captcha_not_field": "Введите код.",
    "captcha_wrong": "Код введен некорректно. Попробуйте еще раз",
}


export const en_language = {
    "auth": "Log in",
    "reg": "Registration",
    "recovery": "Recovery",
    "error_password": "Incorrect password, please try again.",
    "not_active_account": "Your account is inactive. A new activation message has been sent to you.",
    "not_fields": "Fill in all the fields.",
    "not_auth": "The user is not registered.",
    "next_email": "Continue with email",
    "next_pass": "Continue with password",
    "next_username": "Continue with username",
    "forgot_pass": "Forgot password?",
    "authentification": " Already registered? ",
    "authorization": "Authorization",
    "not_register": " Not registered? ",
    "register": "Register" ,
    "enter_pass": "Enter your password...",
    "enter_re_pass": "Enter your password again...",
    "enter_email": "Enter your email address...",
    "enter_username": "Enter your username...",
    "active_email": "A user with such an email has already been registered.",
    "password_common": "The entered password is too widespread. Try another one.",
    "not_email_aviable": "Enter the correct email address!",
    "password_match": "Passwords don't match.",
    "password_numbers": "The entered password consists only of digits. Try another one.",
    "password_short": "The entered password is too short. It must contain at least 8 characters!",
    "active_username": "A user with that name has already been registered.",
    "activation": "The activation message has been sent to the email address.",
    "activation_reset": "The message with the instructions was sent again to the post office. You will be redirected in a few seconds.",
    "error_mail_send": "Error sending the message",
    "captcha_input": "Enter the code here...",
    "captcha_not_field": "Enter the code.",
    "captcha_wrong": "The code was entered incorrectly. Try again.",
}