export const ru_language = {
    "text_span_start_page": "Сила визулальной перспективы для вашей команды",
    "btn_start_page": "Зарегестрируйтесь - это бесплатно!",
    "marked_boards": "Отмеченные доски",
    "last_boards": "Остальные таблицы",
    "create_board": "Создать доску",
    "notifications":"Уведомления",
    "no_notifications":"Нет непрочитанных уведомлений",
    "invation_on": "Приглашение от ",
    "invation_board": "Приглашение на доску ",
    "accepted_invation": "Вы приняли предложение",
    "rejected_invation": "Вы отказались от предложения",
    "accepted": "Принять",
    "rejected": "Отказаться",
    "user_invation":" от пользователя ",
    "header_board": "Заголовок доски",
    "board_name":"Укажите название доски.",
    "create":"Создать",
    "background":"Фон",
    "settings":"Настройки",
    "logout":"Выйти",
    "home":"Дом",
    "new_page":"Новая доска",
    "light_mode": "Белая тема",
    "dark_mode": "Темная тема",
    "сard":"Карточка",
    "list":"Список",
    "tag":"Метки",
    "member":"Участники",
    "time":"Срок",
    "color_tooltip":"Цвет:",
    "name_tooltip":"название:",
    "time_not_soon":"Срок карточки истекает не скоро",
    "time_recently_ended":"Срок действия карточки недавно закончился",
    "time_ended":"Срок действия карточки давно закончился",
    "time_ok":"Карточка выполнена",
    "time_end_soon":"Срок действия карточки закончится в течении 24 часов",
    "open_card":"Открыть карточку",
    "change_tag":"Изменить метки",
    "change_member":"Изменить участников",
    "change_time":"Изменить дату",
    "change":"Переместить",
    "delete":"Удалить",
    "save":"Сохранить",
    "card_attachments":"Эта карточка с вложениями",
    "card_description":"Эта карточка с описанием",
    "card_signed":"Вы подписаны на эту карточку",
    "change_language":"Смена языка",
    "board":"Доска",
    "table":"Таблица",
    "panel":"Панель",
    "share_board":"Поделиться доской",
    "error_member":"Похоже, этот человек еще не участник Notesmaker. Добавьте адрес его электронной почты, чтобы пригласить.",
    "creator_board":"Создатель доски",
    "admin_board":"Администратор доски",
    "member_board":"Участник доски",
    "delete_board":"Удалить доску",
    "delete_in_board":"Удалить с доски",
    "exit":"Выйти с доски",
    "expectation":"Ожидание ответа на приглашение",
    "view_mode":"Режим просмотра",
    "share":"Поделиться",
    "email":"Адрес электронной почты...",
    "add_table":"Добавьте еще одну колонку",
    "add_header":"Добавить заголовок",
    "input_header":'Введите заголовок',
    "add_item":"Добавить карточку",
    "move_table_conf":"Переместить список",
    "delete_table_conf":"Удалить список",
    "delete_table":"Удаление списка",
    "confirmation_delete":"Вы точно хотите удалить список?",
    "move_table":"Перемещение",
    "choose_move":"Выберите куда поставить таблицу...",
    "move":"Переместить",
    "now_current":" (текущая)",
    "name_card":"Название",
    "done":"Выполнено",
    "expired":"Просрочен",
    "deadline_expire":"Срок истекает",
    "deadline_not_soon":"Истекает не скоро",
    "сards":"Карточек",
    "no_dedline":"Без срока",
    "cards_table":"Карточки по колонкам",
    "cards_dedline":"Карточки по дате выполнения",
    "cards_members":"Карточки по участникам",
    "cards_tags":"Карточки по меткам",
    "add_creator":"Сделать создателем доски",
    "remove_paticipant":"Понизить до участника",
    "remove_member":"Удалить участника из доски",
    'add_admin':'Сделать администратом доски',
    'editing_tag':'Ректирование метки',
    'name_tag':'Название метки',
    'creature_tag':'Создание метки',
    'attachments':'Вложения',
    'add_in_card_member':'Добавить на карточку',
    'name_tag_dot':'Название:',
    'color_tag':'Цвет:',
    'date':'Дату',
    'actions':'Действия',
    'delete_card':'Удаление карточки',
    'delete_tag_conf':'Вы точно хотите удалить карточку?',
    'description':'Описание',
    'add_description':'Добавьте более подробное описаниe...',
    'remove_cover':'Убрать обложку',
    'in_list':'в колонке ',
    'add_new_tag':'Создать новую метку',
    'download':'Загрузить',
    'site':'Посетить сайт',


    'choose_list':'Выберите колонку...',
    '':'',
    '':'',
    '':'',
    '':'',
    '':'',
    '':'',
    '':'',
    '':'',
    '':'',
    '':'',




    "auth": "Авторизация",
    "reg": "Регистрация",
    "recovery": "Восстановление",
    "error_password": "Неправильный пароль, попробуйте еще раз.",
    "not_active_account": "Ваш аккаунт не активен. Вам выслано новое сообщение с активацией.",
    "not_fields": "Заполните поля.",
    "not_auth": "Пользователь не зарегистрирован.",
    "next_email": "Продолжить с почтой",
    "next_pass": "Продолжить с паролем",
    "next_username": "Продолжить с имени пользователя",
    "forgot_pass": "Забыли пароль?",
    "authentification": " Уже зарегестрированы? ",
    "authorization": "Войти",
    "not_register": " Не зарегистрированы? ",
    "register": "Зарегистрироваться" ,
    "enter_pass": "Введите ваш пароль...",
    "enter_re_pass": "Введите ваш пароль еще раз...",
    "enter_email": "Введите вашу почту...",
    "enter_username": "Введите ваше имя пользователя...",
    "active_email": "Пользователь с такой почтой уже зарегистрирован.",
    "password_common": "Введённый пароль слишком широко распространён. Попробуйте другой.",
    "not_email_aviable": "Введите правильный адрес электронной почты!",
    "password_match": "Пароли не совпадают.",
    "password_numbers": "Введённый пароль состоит только из цифр. Попробуйте другой.",
    "password_short": "Введённый пароль слишком короткий. Он должен содержать как минимум 8 символов!",
    "active_username": "Пользователь с таким именем уже зарегистрирован.",
    "activation": "Сообщение с активацией отправлено на почту.",
    "activation_reset": "Сообщение с инструкцией отправлено повторно на почту. Через несколько секунд вы будете перенаправлены.",
    "error_mail_send": "Ошибка при отправке сообщения",
    "captcha_input": "Введите код сюда...",
    "captcha_not_field": "Введите код.",
    "captcha_wrong": "Код введен некорректно. Попробуйте еще раз",
}


export const en_language = {
    "marked_boards": "Marked boards",
    "last_boards": "Other boards",
    "create_board": "Create a board",
    "notifications":"Notifications",
    "no_notifications":"No unread notifications",
    "invation_on": "An invitation from ",
    "invation_board": "Invitation to the board ",
    "accepted_invation": "Have you accepted the offer ",
    "rejected_invation": "You refused the offer ",
    "accepted": "Accept",
    "rejected": "Refuse",
    "user_invation":" from the user ",
    "header_board": "The title of the board",
    "board_name":"Specify the name of the board.",
    "create":"To create",
    "background":"Background",
    "settings":"Settings",
    "logout":"Logout",
    "home":"Home",
    "new_page":"New board",
    "light_mode": "Light Mode",
    "dark_mode": "Dark Mode",
    "сard":"Card",
    "list":"List",
    "tag":"Tags",
    "member":"Members",
    "time":"Time",
    "color_tooltip":"Color:",
    "name_tooltip":"name:",
    "time_not_soon":"The card will not expire soon",
    "time_recently_ended":"The validity period of the card has recently expired",
    "time_ended":"The validity period of the card has long expired",
    "time_ok":"The card is completed",
    "time_end_soon":"The card will expire within 24 hours",
    "open_card":"Open a card",
    "change_tag":"Change labels",
    "change_member":"Change participants",
    "change_time":"Change the date",
    "change":"Move",
    "delete":"Remove",
    "save":"Save",
    "card_attachments":"This card has attachments",
    "card_description":"This card has a description",
    "card_signed":"You are subscribed to this card",
    "change_language":"Changing the language",
    "board":"Board",
    "table":"Table",
    "panel":"Panel",
    "share_board":"Share the board",
    "error_member":"It looks like this person is not yet a member of Notesmaker. Add his email address to invite him.",
    "creator_board":"Board creator",
    "admin_board":"Board administrator",
    "member_board":"Board member",
    "delete_board":"Remove board",
    "delete_in_board":"Remove from the board",
    "exit":"Get off the board",
    "expectation":"Waiting for a response to an invitation",
    "view_mode":"Viewing mode",
    "share":"Share",
    "email":"Email address...",
    "add_table":"Add another column",
    "add_header":"Add a title",
    "input_header":'Enter the title',
    "add_item":"Add a card",
    "move_table_conf":"Move list",
    "delete_table_conf":"Delete list",
    "delete_table":"Deleting a list",
    "confirmation_delete":"Are you sure you want to delete the list?",
    "move_table":"Moving",
    "choose_move":"Choose where to put the table...",
    "move":"Move",
    "now_current":" (current)",
    "name_card":"Name",
    "done":"Done",
    "expired":"Expired",
    "deadline_expire":"The deadline is about to expire",
    "deadline_not_soon":"It's not going to expire soon",
    "сards":"Cards",
    "no_dedline":"No deadline",
    "cards_table":"Cards by column",
    "cards_dedline":"Cards by completion date",
    "cards_members":"Cards by participants",
    "cards_tags":"Cards by tags",
    "add_creator":"Make a board creator",
    "remove_paticipant":"Demote to a member",
    "remove_member":"Remove participant from the board",
    'add_admin':'Make the board administrator',
    'editing_tag':'Label rectification',
    'name_tag':'Label name',
    'creature_tag':'Creating a label',
    'attachments':'Attachments',
    'add_in_card_member':'Add to the card',
    'name_tag_dot':'Title:',
    'color_tag':'Colour:',
    'date':'Date',
    'actions':'Actions',
    'delete_card':'Deleting a card',
    'delete_tag_conf':'Are you sure you want to delete the card?',
    'description':'Description',
    'add_description':'Add a more detailed description...',
    'remove_cover':'Remove the cover',
    'in_list':'in the column ',
    'add_new_tag':'Create a new label',
    'download':'Download',
    'site':'Visit the website',

    "text_span_start_page": "The power of visual perspective for your team",
    "btn_start_page": "Register - it's free!",
    "auth": "Log in",
    "reg": "Registration",
    "recovery": "Recovery",
    "error_password": "Incorrect password, please try again.",
    "not_active_account": "Your account is inactive. A new activation message has been sent to you.",
    "not_fields": "Fill in all the fields.",
    "not_auth": "The user is not registered.",
    "next_email": "Continue with email",
    "next_pass": "Continue with password",
    "next_username": "Continue with username",
    "forgot_pass": "Forgot password?",
    "authentification": " Already registered? ",
    "authorization": "Authorization",
    "not_register": " Not registered? ",
    "register": "Register" ,
    "enter_pass": "Enter your password...",
    "enter_re_pass": "Enter your password again...",
    "enter_email": "Enter your email address...",
    "enter_username": "Enter your username...",
    "active_email": "A user with such an email has already been registered.",
    "password_common": "The entered password is too widespread. Try another one.",
    "not_email_aviable": "Enter the correct email address!",
    "password_match": "Passwords don't match.",
    "password_numbers": "The entered password consists only of digits. Try another one.",
    "password_short": "The entered password is too short. It must contain at least 8 characters!",
    "active_username": "A user with that name has already been registered.",
    "activation": "The activation message has been sent to the email address.",
    "activation_reset": "The message with the instructions was sent again to the post office. You will be redirected in a few seconds.",
    "error_mail_send": "Error sending the message",
    "captcha_input": "Enter the code here...",
    "captcha_not_field": "Enter the code.",
    "captcha_wrong": "The code was entered incorrectly. Try again.",
}