# Generated by Django 5.0.2 on 2024-04-19 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('cover', models.URLField(blank=True, null=True)),
                ('users', models.ManyToManyField(blank=True, related_name='board', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Страницы',
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_invite', to='backend_api.board')),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitee', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inviter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Приглашения',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('comment', models.TextField(blank=True, null=True)),
                ('position', models.PositiveIntegerField()),
                ('members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Элементы таблицы',
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document', models.FileField(blank=True, null=True, upload_to='frontend_notes/src/assets')),
                ('site', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('extension', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment', to='backend_api.item')),
            ],
            options={
                'verbose_name_plural': 'Вложения',
            },
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('complete', models.BooleanField(default=False)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datepicker', to='backend_api.item')),
            ],
            options={
                'verbose_name_plural': 'Дата на элементе',
            },
        ),
        migrations.CreateModel(
            name='Rights',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('right', models.CharField(default='participant', max_length=50)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rights', to='backend_api.board')),
            ],
            options={
                'verbose_name_plural': 'Разрешения',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('position', models.PositiveIntegerField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='backend_api.board')),
            ],
            options={
                'verbose_name_plural': 'Таблицы',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table', to='backend_api.table'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='backend_api.board')),
                ('item', models.ManyToManyField(blank=True, related_name='tag', to='backend_api.item')),
            ],
            options={
                'verbose_name_plural': 'Тэги на элементе',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('avatar', models.CharField(max_length=150)),
                ('board_like', models.ManyToManyField(blank=True, related_name='board', to='backend_api.board')),
                ('rights', models.ManyToManyField(blank=True, related_name='rights', to='backend_api.rights')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Информация о пользователе',
            },
        ),
    ]
